### ISSUE TITLE
Incorrect padding x00 , it should be PKCS#7

### ISSUE THREAD

**Issue by soadyp** [Sumu-Ning/AES#4]
The padding used x00 up to the block boundary is incorrect.   AES CBC is supposed to use PKCS#7  padding.  There is actually a chance of losing data when removing x00 based on this padding approach apara from the fact that it is the wrong padding.

The pkcs 7 padding in simple terms is:
bytes needed to fill last block / padding to use
01
0202
030303
04040404
etc to
0E............0E for padd 15 bytes
and
importantly
of the plain text actually plain hex is a better description is a multiple of the block size
and although no padding would appear to be necessary, a complete extra block is required with
1010101010......10   16 times for 16 byte block size

This is important if 2 systems are to share messages successfully.   The Padding needs to be consistent and correct.

**Comment by Sumu-Ning** [comment]
Thank you for your feedback, Phil!

I understand what you are saying. However, pkcs7 is not part of AES, but more an agreement or convention between parties. I thought I would just leave it for the users to decide what padding they want to use.

Since you mentioned this, let me write some padding utilities really quick, and keep the backward compatibility. They should be ready by tonight, hopefully :).

**Comment by soadyp** [comment]
You are right it isnt actually part of the AES CBC standard. It is more of the case most tools use PKCS 5 or 7 when padding.   We are encrypting in browser and sending to sap and vice versa. So a consistent approach is important. I have tested your tool AES CBC a lot.  All seems fine except of the padding. So a pkcs padding would be fantastic.   We did have some performance challenges. Decrypting in abap was taking about 1 sec per 15k. I will check monday for Updates. 
Nice job BTW.  :)

**Comment by Sumu-Ning** [comment]
I added the support for PKCS 7 padding, and the default is still "No padding (fill '00' to full block).
PKCS 5 is padding for 8-byte block, and AES is using 16-byte block. Therefore, I guess it is not possible?

Also, I refactored the code to use internal table instead of xstring as the intermittent storeage, and hopefully this can improve the performance. I still don't know how to handle the concatenation of Xstring, it would be great if ABAP had something similar to StringBuilder in Java.

I am very glad that it is useful to other people, but I did not expect that it would be used for large chunk of data :p. Please let me know whether it works for your scenario, and thank you again for your feedback to make it better.

**Comment by soadyp** [comment]
Pkcs 5 is just a subset of pkcs7. So no need to offer. Thanks for your
efforts.  I will download and test .

The stringbuilder tool is a weakness
In abap yes. Im used to c# and miss several things in abap. We deliver to
customers in different releases so i cant use new 7.4 features anyway :(

I was actually considering to try changing the internal tables into xstring
and access mit offset To see if that is faster.
Cheers Phil.

**Comment by soadyp** [comment]
Tested, pkcs 7 padding working as excpected ;) Nice work

**Comment by Sumu-Ning** [comment]
Glad to hear that. Do you have some statistics about the performance? getting better or worse? :)

**Comment by soadyp** [comment]
Performance similar.
40K takes about 3 secs

_Phil Soady_

_Mobile_:\* +49 1520 604 3313 _| *Email_:
phil.soady@gmail.com_phil.soady@gmail.com
phil.soady@gmail.com_(Private)

phil.soady@gmail.com\* phil.soady@gmail.com*
